# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('lxspline_rcpp_hello_world', PACKAGE = 'lxspline')
}

Tnorm <- function(){ .Call('sourceCpp_0_Tnorm' , PACKAGE = 'lxspline')}
BivNProb <- function(){ .Call('sourceCpp_0_BivNProb' , PACKAGE = 'lxspline')}
TriNProb <- Rcpp:::sourceCppFunction(function(mean, cv) {}, FALSE, `.sourceCpp_0_DLLInfo`, 'sourceCpp_0_TriNProb')
sampleBetas <- Rcpp:::sourceCppFunction(function(ttY, ttX, tbetas, LAM, intLAM, p, tau) {}, FALSE, `.sourceCpp_0_DLLInfo`, 'sourceCpp_0_sampleBetas')
sinsertBeta <- Rcpp:::sourceCppFunction(function(tY, Xidx, ctau, tp, lam) {}, FALSE, `.sourceCpp_0_DLLInfo`, 'sourceCpp_0_sinsertBeta')
sdeleteBeta <- Rcpp:::sourceCppFunction(function(tY, Xidx, ctau, tp, lam) {}, FALSE, `.sourceCpp_0_DLLInfo`, 'sourceCpp_0_sdeleteBeta')
shapesplineInsert <- Rcpp:::sourceCppFunction(function(k, tp, txi, tdeg, tCBX, tpos) {}, FALSE, `.sourceCpp_0_DLLInfo`, 'sourceCpp_0_shapesplineInsert')
shapesplineDelete <- Rcpp:::sourceCppFunction(function(k, tp, txi, tdeg, tCBX, tpos) {}, FALSE, `.sourceCpp_0_DLLInfo`, 'sourceCpp_0_shapesplineDelete')
rtmvn <- Rcpp:::sourceCppFunction(function(tMean, tVar) {}, FALSE, `.sourceCpp_0_DLLInfo`, 'sourceCpp_0_rtmvn')
qcopy <- Rcpp:::sourceCppFunction(function(a, b, c, d) {}, FALSE, `.sourceCpp_0_DLLInfo`, 'sourceCpp_0_qcopy')
